#!/usr/bin/env python3
"""Generate end-to-end snapshot test cases for the root package.

Selects representative .ssa files from test/<category>/ (2-3 per category) and
emits a MoonBit test file (qbe_snapshot_test.mbt) where each test embeds the
IL source and asserts the emitted assembly via `inspect`.

The expected assembly snapshots are filled in by `moon test --update` and
verified against the reference C QBE via `python compare.py`.

Usage:
    python tools/gen_snapshot_mbt.py            # regenerate the skeleton
    moon test --update                          # (re)fill the snapshots
"""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTDIR = os.path.join(ROOT, "test")
OUT = os.path.join(ROOT, "qbe_snapshot_test.mbt")

CATEGORIES = ["core", "fold", "abi", "isel", "regalloc", "emit", "programs"]
PER_CATEGORY = 2
# skip inputs that are not pure modules (CLI-specific or oversized)
MAX_LINES = 60


def pick(category: str):
    files = sorted(glob.glob(os.path.join(TESTDIR, category, "*.ssa")))
    files = [f for f in files if os.path.getsize(os.path.join(f, "x" if False else f)) >= 0]
    files.sort(key=lambda f: (len(open(f, encoding="utf8", errors="replace").readlines()), f))
    chosen = []
    for f in files:
        if len(open(f, encoding="utf8", errors="replace").readlines()) > MAX_LINES:
            continue
        chosen.append(f)
        if len(chosen) == PER_CATEGORY:
            break
    return chosen


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def main():
    tests = []
    for cat in CATEGORIES:
        for f in pick(cat):
            src = open(f, encoding="utf8", errors="replace").read()
            if "\t" in src:
                src = src.replace("\t", "    ")
            name = os.path.splitext(os.path.basename(f))[0]
            block = f'''///|
test "e2e {cat}: {name}" {{
  let src =
'''
            for line in src.split("\n"):
                if line.strip() == "":
                    continue
                block += "    #|" + line + "\n"
            block += '''    #|
  match compile(src) {
    Ok(assembly) => inspect!(assembly, content="")
    Err(e) => fail("compile failed: \\{e}")
  }
}
'''
            tests.append(block)

    header = '''///|
// End-to-end snapshot tests: representative .ssa inputs from test/ compiled
// through the full amd64_sysv pipeline.
//
// Generated by `python tools/gen_snapshot_mbt.py`; expected assembly snapshots
// are filled by `moon test --update` and cross-checked against the reference
// C QBE with `python compare.py --asm`. Do not edit the sources by hand.

'''
    with open(OUT, "w", encoding="utf8", newline="\n") as fh:
        fh.write(header + "\n".join(tests))
    print(f"wrote {OUT} with {len(tests)} tests")


if __name__ == "__main__":
    main()
